spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/dvdrental
    username: postgres
    password: pass123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect